// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("http://localhost:3000")
    await driver.findElement(By.name("nombre")).click()
    await driver.findElement(By.name("nombre")).sendKeys("test1")
    await driver.findElement(By.name("sala")).click()
    await driver.findElement(By.name("sala")).sendKeys("hello")
    await driver.findElement(By.css(".btn")).click()
  })
})
